apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ds0qo47jr-python
  janus-idp.io/tekton: ds0qo47jr-python
  backstage.io/kubernetes-id: ds0qo47jr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ds0qo47jr-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
